################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
SimpliciTI/Components/simpliciti/nwk_applications/nwk_freq.obj: ../SimpliciTI/Components/simpliciti/nwk_applications/nwk_freq.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.1/bin/cl430" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_config.dat" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_nwk_config.dat"  -vmspx --abi=eabi --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.1/include" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/HAL" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/User" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/Sensors_API" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/mrfi" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk_applications" -g --define=__MSP430FR5739__ --define=MRFI_CC1100 --define=ENABLE_SENSOR_DATA_STATUSx --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SimpliciTI/Components/simpliciti/nwk_applications/nwk_freq.pp" --obj_directory="SimpliciTI/Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SimpliciTI/Components/simpliciti/nwk_applications/nwk_ioctl.obj: ../SimpliciTI/Components/simpliciti/nwk_applications/nwk_ioctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.1/bin/cl430" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_config.dat" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_nwk_config.dat"  -vmspx --abi=eabi --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.1/include" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/HAL" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/User" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/Sensors_API" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/mrfi" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk_applications" -g --define=__MSP430FR5739__ --define=MRFI_CC1100 --define=ENABLE_SENSOR_DATA_STATUSx --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SimpliciTI/Components/simpliciti/nwk_applications/nwk_ioctl.pp" --obj_directory="SimpliciTI/Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SimpliciTI/Components/simpliciti/nwk_applications/nwk_join.obj: ../SimpliciTI/Components/simpliciti/nwk_applications/nwk_join.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.1/bin/cl430" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_config.dat" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_nwk_config.dat"  -vmspx --abi=eabi --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.1/include" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/HAL" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/User" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/Sensors_API" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/mrfi" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk_applications" -g --define=__MSP430FR5739__ --define=MRFI_CC1100 --define=ENABLE_SENSOR_DATA_STATUSx --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SimpliciTI/Components/simpliciti/nwk_applications/nwk_join.pp" --obj_directory="SimpliciTI/Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SimpliciTI/Components/simpliciti/nwk_applications/nwk_link.obj: ../SimpliciTI/Components/simpliciti/nwk_applications/nwk_link.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.1/bin/cl430" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_config.dat" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_nwk_config.dat"  -vmspx --abi=eabi --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.1/include" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/HAL" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/User" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/Sensors_API" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/mrfi" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk_applications" -g --define=__MSP430FR5739__ --define=MRFI_CC1100 --define=ENABLE_SENSOR_DATA_STATUSx --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SimpliciTI/Components/simpliciti/nwk_applications/nwk_link.pp" --obj_directory="SimpliciTI/Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SimpliciTI/Components/simpliciti/nwk_applications/nwk_mgmt.obj: ../SimpliciTI/Components/simpliciti/nwk_applications/nwk_mgmt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.1/bin/cl430" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_config.dat" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_nwk_config.dat"  -vmspx --abi=eabi --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.1/include" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/HAL" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/User" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/Sensors_API" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/mrfi" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk_applications" -g --define=__MSP430FR5739__ --define=MRFI_CC1100 --define=ENABLE_SENSOR_DATA_STATUSx --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SimpliciTI/Components/simpliciti/nwk_applications/nwk_mgmt.pp" --obj_directory="SimpliciTI/Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SimpliciTI/Components/simpliciti/nwk_applications/nwk_ping.obj: ../SimpliciTI/Components/simpliciti/nwk_applications/nwk_ping.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.1/bin/cl430" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_config.dat" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_nwk_config.dat"  -vmspx --abi=eabi --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.1/include" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/HAL" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/User" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/Sensors_API" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/mrfi" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk_applications" -g --define=__MSP430FR5739__ --define=MRFI_CC1100 --define=ENABLE_SENSOR_DATA_STATUSx --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SimpliciTI/Components/simpliciti/nwk_applications/nwk_ping.pp" --obj_directory="SimpliciTI/Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

SimpliciTI/Components/simpliciti/nwk_applications/nwk_security.obj: ../SimpliciTI/Components/simpliciti/nwk_applications/nwk_security.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"c:/ti/ccsv6/tools/compiler/msp430_4.3.1/bin/cl430" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_config.dat" --cmd_file="C:\Users\Marcio\Desktop\Angstrom\angstrom_ccs_workspace\SH_Test0\SimpliciTI\Configuration\smpl_nwk_config.dat"  -vmspx --abi=eabi --include_path="c:/ti/ccsv6/ccs_base/msp430/include" --include_path="c:/ti/ccsv6/tools/compiler/msp430_4.3.1/include" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/HAL" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/User" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/Sensors_API" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/mrfi" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk" --include_path="C:/Users/Marcio/Desktop/Angstrom/angstrom_ccs_workspace/SH_Test0/SimpliciTI/Components/simpliciti/nwk_applications" -g --define=__MSP430FR5739__ --define=MRFI_CC1100 --define=ENABLE_SENSOR_DATA_STATUSx --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=minimal --preproc_with_compile --preproc_dependency="SimpliciTI/Components/simpliciti/nwk_applications/nwk_security.pp" --obj_directory="SimpliciTI/Components/simpliciti/nwk_applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


